class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<NotesModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <NotesModel>[];
      json['data'].forEach((v) {
        data!.add(new NotesModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NotesModel {
  int? id;
  String? title;
  String? color;
  String? type;
  String? drawingData;
  String? description;
  int? workspaceId;
  String? creatorId;
  String? createdAt;
  String? updatedAt;

  NotesModel(
      {this.id,
        this.title,
        this.color,
        this.type,
        this.drawingData,
        this.description,
        this.workspaceId,
        this.creatorId,
        this.createdAt,
        this.updatedAt});

  NotesModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    color = json['color'];
    type = json['type'];
    drawingData = json['drawing_data'];
    description = json['description'];
    workspaceId = json['workspace_id'];
    creatorId = json['creator_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['color'] = this.color;
    data['type'] = this.type;
    data['drawing_data'] = this.drawingData;
    data['description'] = this.description;
    data['workspace_id'] = this.workspaceId;
    data['creator_id'] = this.creatorId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
