class Autogenerated {
  Original? original;

  Autogenerated({this.original});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    original = json['original'] != null
        ? new Original.fromJson(json['original'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();

    if (this.original != null) {
      data['original'] = this.original!.toJson();
    }
    return data;
  }
}

class Original {
  bool? error;
  String? message;
  MindMapModel? data;

  Original({this.error, this.message, this.data});

  Original.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    data = json['data'] != null ? new MindMapModel.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class MindMapModel {
  String? id;
  String? topic;
  String? link;
  bool? isroot;
  int? level;
  List<Children>? children;

  MindMapModel(
      {this.id, this.topic, this.link, this.isroot, this.level, this.children});

  MindMapModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    topic = json['topic'];
    link = json['link'];
    isroot = json['isroot'];
    level = json['level'];
    if (json['children'] != null) {
      children = <Children>[];
      json['children'].forEach((v) {
        children!.add(new Children.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['topic'] = this.topic;
    data['link'] = this.link;
    data['isroot'] = this.isroot;
    data['level'] = this.level;
    if (this.children != null) {
      data['children'] = this.children!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Children {
  String? id;
  String? topic;
  int? level;
  String? link;
  List<Children>? children;

  Children({this.id, this.topic, this.level, this.children});

  Children.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    topic = json['topic'];
    level = json['level'];
    link = json['link'];
    if (json['children'] != null) {
      children = <Children>[];
      json['children'].forEach((v) {
        children!.add(new Children.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['topic'] = this.topic;
    data['level'] = this.level;
    data['link'] = this.link;
    if (this.children != null) {
      data['children'] = this.children!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
