class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<CandidateStatusModel>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <CandidateStatusModel>[];
      json['data'].forEach((v) {
        data!.add(new CandidateStatusModel.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class CandidateStatusModel {
  int? id;
  String? name;
  int? order;
  String? color;
  String? createdAt;
  String? updatedAt;
  bool? canEdit;
  bool? canDelete;

  CandidateStatusModel(
      {this.id,
        this.name,
        this.order,
        this.color,
        this.createdAt,
        this.updatedAt,
        this.canEdit,
        this.canDelete});

  CandidateStatusModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    order = json['order'];
    color = json['color'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['order'] = this.order;
    data['color'] = this.color;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}

class Permissions {
  bool? canEdit;
  bool? canDelete;

  Permissions({this.canEdit, this.canDelete});

  Permissions.fromJson(Map<String, dynamic> json) {
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}
