class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<LeadModel>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <LeadModel>[];
      json['data'].forEach((v) {
        data!.add(new LeadModel.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class LeadModel {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? phone;
  String? countryCode;
  String? countryIsoCode;
  int? leadSourceId;
  String? leadSource;
  int? leadStageId;
  String? leadStage;
  String? leadStageColor;
  int? assignedTo;
  AssignedUser? assignedUser;
  String? jobTitle;
  String? industry;
  String? company;
  String? website;
  String? linkedin;
  String? instagram;
  String? facebook;
  String? pinterest;
  String? city;
  String? state;
  String? zip;
  String? country;
  bool? isConverted;
  List<FollowUps>? followUps;
  String? createdAt;
  String? updatedAt;

  LeadModel(
      {this.id,
        this.firstName,
        this.lastName,
        this.email,
        this.phone,
        this.countryCode,
        this.countryIsoCode,
        this.leadSourceId,
        this.leadSource,
        this.leadStageId,
        this.leadStage,
        this.assignedTo,
        this.assignedUser,
        this.leadStageColor,
        this.jobTitle,
        this.industry,
        this.company,
        this.website,
        this.linkedin,
        this.instagram,
        this.facebook,
        this.pinterest,
        this.city,
        this.state,
        this.zip,
        this.country,
        this.isConverted,
        this.followUps,
        this.createdAt,
        this.updatedAt});
  factory LeadModel.empty() {
    return LeadModel(
      id: 0,
      firstName: '',
      lastName: '',
      email: '',
      phone: '',
      countryCode: '',
      countryIsoCode: '',
      leadSourceId: 0,
      leadSource: '',
      leadStageId: 0,
      leadStage: '',
      assignedTo: 0,
      assignedUser: AssignedUser.empty(),
      jobTitle: '',
      leadStageColor: '',
      industry: '',
      company: '',
      website: '',
      linkedin: '',
      instagram: '',
      facebook: '',
      pinterest: '',
      city: '',
      state: '',
      zip: '',
      country: '',
      isConverted: false,
      followUps: [],
      createdAt: '',
      updatedAt: '',
    );
  }

  LeadModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    phone = json['phone'];
    countryCode = json['country_code'];
    countryIsoCode = json['country_iso_code'];
    leadSourceId = json['lead_source_id'];
    leadSource = json['lead_source'];
    leadStageColor = json['lead_stage_color'];
    leadStageId = json['lead_stage_id'];
    leadStage = json['lead_stage'];
    assignedTo = json['assigned_to'];
    assignedUser = json['assigned_user'] != null
        ? new AssignedUser.fromJson(json['assigned_user'])
        : null;
    jobTitle = json['job_title'];
    industry = json['industry'];
    company = json['company'];
    website = json['website'];
    linkedin = json['linkedin'];
    instagram = json['instagram'];
    facebook = json['facebook'];
    pinterest = json['pinterest'];
    city = json['city'];
    state = json['state'];
    zip = json['zip'];
    country = json['country'];
    isConverted = json['isConverted'];
    if (json['follow_ups'] != null) {
      followUps = <FollowUps>[];
      json['follow_ups'].forEach((v) {
        followUps!.add(new FollowUps.fromJson(v));
      });
    }
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['country_code'] = this.countryCode;
    data['country_iso_code'] = this.countryIsoCode;
    data['lead_source_id'] = this.leadSourceId;
    data['lead_source'] = this.leadSource;
    data['lead_stage_id'] = this.leadStageId;
    data['lead_stage_color'] = this.leadStageColor;
    data['lead_stage'] = this.leadStage;
    data['assigned_to'] = this.assignedTo;
    if (this.assignedUser != null) {
      data['assigned_user'] = this.assignedUser!.toJson();
    }
    data['job_title'] = this.jobTitle;
    data['industry'] = this.industry;
    data['company'] = this.company;
    data['website'] = this.website;
    data['linkedin'] = this.linkedin;
    data['instagram'] = this.instagram;
    data['facebook'] = this.facebook;
    data['pinterest'] = this.pinterest;
    data['city'] = this.city;
    data['state'] = this.state;
    data['zip'] = this.zip;
    data['country'] = this.country;
    data['isConverted'] = this.isConverted;
    if (this.followUps != null) {
      data['follow_ups'] = this.followUps!.map((v) => v.toJson()).toList();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class AssignedUser {
  int? id;
  String? name;
  String? email;
  String? profilePicture;

  AssignedUser({this.id, this.name, this.email, this.profilePicture});
  factory AssignedUser.empty() {
    return AssignedUser(
      id: 0,
      name: '',
      email: '',
      profilePicture: '',
    );
  }
  AssignedUser.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    profilePicture = json['profile_picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['profile_picture'] = this.profilePicture;
    return data;
  }
}

class FollowUps {
  int? id;
  String? followUpAt;
  String? type;
  String? status;
  String? note;
  AssignedUser? assignedTo;
  String? createdAt;
  String? updatedAt;

  FollowUps(
      {this.id,
        this.followUpAt,
        this.type,
        this.status,
        this.note,
        this.assignedTo,
        this.createdAt,
        this.updatedAt});
  factory FollowUps.empty() {
    return FollowUps(
      id: null,
      followUpAt: '',
      type: '',
      status: '',
      note: '',
      assignedTo: AssignedUser.empty(),
      createdAt: '',
      updatedAt: '',
    );
  }
  FollowUps.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    followUpAt = json['follow_up_at'];
    type = json['type'];
    status = json['status'];
    note = json['note'];
    assignedTo = json['assigned_to'] != null
        ? new AssignedUser.fromJson(json['assigned_to'])
        : null;
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['follow_up_at'] = this.followUpAt;
    data['type'] = this.type;
    data['status'] = this.status;
    data['note'] = this.note;
    if (this.assignedTo != null) {
      data['assigned_to'] = this.assignedTo!.toJson();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class AssignedTo {
  int? id;
  String? name;

  AssignedTo({this.id, this.name});

  AssignedTo.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}

class Permissions {
  bool? canEdit;
  bool? canDelete;

  Permissions({this.canEdit, this.canDelete});

  Permissions.fromJson(Map<String, dynamic> json) {
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}
