class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<LeadSourceModel>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <LeadSourceModel>[];
      json['data'].forEach((v) {
        data!.add(new LeadSourceModel.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class LeadSourceModel {
  int? id;
  String? name;
  String? createdAt;
  String? updatedAt;

  LeadSourceModel({this.id, this.name, this.createdAt, this.updatedAt});

  LeadSourceModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Permissions {
  bool? canDelete;
  bool? canEdit;

  Permissions({this.canDelete, this.canEdit});

  Permissions.fromJson(Map<String, dynamic> json) {
    canDelete = json['can_delete'];
    canEdit = json['can_edit'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_delete'] = this.canDelete;
    data['can_edit'] = this.canEdit;
    return data;
  }
}
