class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<PayslipModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <PayslipModel>[];
      json['data'].forEach((v) {
        data!.add(new PayslipModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PayslipModel {
  int? id;
  PaySlipUser? user;
  String? month;
  double? basicSalary;

  int? workingDays;
  double? lopDays;
  double? paidDays;
  int? bonus;
  int? incentives;
  double? leaveDeduction;
  int? otHours;
  int? otRate;
  int? otPayment;
  List<Allowance>? allowances;
  List<Allowance>? deduction;
  double? totalDeductions;
  double? totalEarnings;
  double? netPay;
  int? status;
  String? statusLabel;
  int? paymentMethodId;
  String? paymentMethod;
  String? paymentDate;
  String? note;
  String? createdAtDate;
  String? updatedAtDate;
  String? createdAtTime;
  String? updatedAtTime;
  String? currentTime;
  String? currentDate;

  PayslipModel(
      {this.id,
        this.user,
        this.month,
        this.basicSalary,
        this.workingDays,
        this.lopDays,
        this.paidDays,
        this.bonus,
        this.incentives,
        this.leaveDeduction,
        this.otHours,
        this.otRate,
        this.otPayment,
        this.allowances,
        this.deduction,
        this.totalDeductions,
        this.totalEarnings,
        this.netPay,
        this.status,
        this.statusLabel,
        this.paymentMethodId,
        this.paymentMethod,
        this.paymentDate,
        this.note,
        this.createdAtDate,
        this.updatedAtDate,
        this.createdAtTime,
        this.updatedAtTime,
        this.currentDate,
        this.currentTime,

      });
  factory PayslipModel.empty() {
    return PayslipModel(
      id: 0,
      user: PaySlipUser(id: 0, name: ''),
      month: '',
      basicSalary: 0,
      workingDays: 0,
      lopDays: 0,
      paidDays: 0,
      bonus: 0,
      incentives: 0,
      leaveDeduction: 0,
      otHours: 0,
      otRate: 0,
      otPayment: 0,
      allowances: [],
      deduction: [],
      totalDeductions: 0,
      totalEarnings: 0,
      netPay: 0,
      status: 0,
      statusLabel: '',
      paymentMethodId: 0,
      paymentMethod: '',
      paymentDate: '',
      note: '',
      createdAtTime: '',
      createdAtDate: '',
      updatedAtTime: '',
      updatedAtDate: '',
      currentTime: '',
      currentDate: '',
    );
  }

  PayslipModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    user = json['user'] != null ? new PaySlipUser.fromJson(json['user']) : null;
    month = json['month'];
    basicSalary = (json['basic_salary'] as num?)?.toDouble();

    workingDays = json['working_days'];
    lopDays = (json['lop_days'] as num?)?.toDouble();
    paidDays = (json['paid_days'] as num?)?.toDouble();
    bonus = json['bonus'];
    incentives = json['incentives'];
    leaveDeduction = (json['leave_deduction'] as num?)?.toDouble();

    otHours = json['ot_hours'];
    otRate = json['ot_rate'];
    otPayment = json['ot_payment'];
    if (json['allowances'] != null) {
      allowances = <Allowance>[];
      json['allowances'].forEach((v) {
        allowances!.add(new Allowance.fromJson(v));
      });
    } if (json['deductions'] != null) {
      deduction = <Allowance>[];
      json['deductions'].forEach((v) {
        deduction!.add(new Allowance.fromJson(v));
      });
    }
    totalDeductions = (json['total_deductions'] as num?)?.toDouble();
    totalEarnings = (json['total_earnings'] as num?)?.toDouble();

    netPay = (json['net_pay'] as num?)?.toDouble();
    status = json['status'];
    statusLabel = json['status_label'];
    paymentMethodId = json['payment_method_id'];
    paymentMethod = json['payment_method'];
    paymentDate = json['payment_date'];
    note = json['note'];
    createdAtDate = json['created_at_date'];
    createdAtTime = json['created_at_time'];
    updatedAtDate = json['updated_at_date'];
    updatedAtTime = json['updated_at_time'];
    currentDate = json['current_date'];
    currentTime = json['current_time'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['month'] = this.month;
    data['basic_salary'] = this.basicSalary;

    data['working_days'] = this.workingDays;
    data['lop_days'] = this.lopDays;
    data['paid_days'] = this.paidDays;
    data['bonus'] = this.bonus;
    data['incentives'] = this.incentives;
    data['leave_deduction'] = this.leaveDeduction;
    data['ot_hours'] = this.otHours;
    data['ot_rate'] = this.otRate;
    data['ot_payment'] = this.otPayment;
    if (this.allowances != null) {
      data['allowances'] = this.allowances!.map((v) => v.toJson()).toList();
    }  if (this.deduction != null) {
      data['deductions'] = this.deduction!.map((v) => v.toJson()).toList();
    }
    data['total_deductions'] = this.totalDeductions;
    data['total_earnings'] = this.totalEarnings;
    data['net_pay'] = this.netPay;
    data['status'] = this.status;
    data['status_label'] = this.statusLabel;
    data['payment_method_id'] = this.paymentMethodId;
    data['payment_method'] = this.paymentMethod;
    data['payment_date'] = this.paymentDate;
    data['note'] = this.note;
    data['created_at_date'] = this.createdAtDate;
    data['created_at_time'] = this.createdAtTime;
    data['updated_at_date'] = this.updatedAtDate;
    data['updated_at_time'] = this.updatedAtTime;
    data['current_date'] = this.currentDate;
    data['current_time'] = this.currentTime;
    return data;
  }
}

class PaySlipUser {
  int? id;
  String? name;
  String? email;
  String? profileImage;


  PaySlipUser({this.id, this.name,this.email,this.profileImage});
  factory PaySlipUser.empty() {
    return PaySlipUser(id: 0, name: '',email:'',profileImage:"");
  }

  PaySlipUser.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    profileImage = json['profile_picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['mail'] = this.email;
    data['profile_picture'] = this.profileImage;
    return data;
  }
}

class Allowance {
  int? id;
  String? title;
  double? amount; // Changed from int? to double?

  Allowance({this.id, this.title, this.amount});

  Allowance.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    // Handle both int and double from JSON
    amount = (json['amount'] is int)
        ? (json['amount'] as int).toDouble()
        : json['amount'] as double?;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['amount'] = amount;
    return data;
  }
}
