class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<CustomFieldModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <CustomFieldModel>[];
      json['data'].forEach((v) {
        data!.add(new CustomFieldModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class CustomFieldModel {
  int? id;
  String? module;
  String? fieldLabel;
  String? fieldType;
  List<String>? options;
  String? required;
  String? showInTable;

  CustomFieldModel({
    this.id,
    this.module,
    this.fieldLabel,
    this.fieldType,
    this.options,
    this.required,
    this.showInTable,
  });

  CustomFieldModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    module = json['module'];
    fieldLabel = json['field_label'];
    fieldType = json['field_type'];
    options = json['options'] != null
        ? List<String>.from(json['options'])
        : [];
    required = json['required'];
    showInTable = json['show_in_table'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['module'] = this.module;
    data['field_label'] = this.fieldLabel;
    data['field_type'] = this.fieldType;
    data['options'] = this.options;
    data['required'] = this.required;
    data['show_in_table'] = this.showInTable;
    return data;
  }

  CustomFieldModel copyWith({
    int? id,
    String? module,
    String? fieldLabel,
    String? fieldType,
    List<String>? options,
    String? required,
    String? showInTable,
  }) {
    return CustomFieldModel(
      id: id ?? this.id,
      module: module ?? this.module,
      fieldLabel: fieldLabel ?? this.fieldLabel,
      fieldType: fieldType ?? this.fieldType,
      options: options ?? this.options,
      required: required ?? this.required,
      showInTable: showInTable ?? this.showInTable,
    );
  }

  // Empty factory method that returns an empty CustomFieldModel
  factory CustomFieldModel.empty() {
    return CustomFieldModel(
      id: null,
      module: null,
      fieldLabel: null,
      fieldType: null,
      options: [],
      required: null,
      showInTable: null,
    );
  }
}


