class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<CandidateAttachment>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <CandidateAttachment>[];
      json['data'].forEach((v) {
        data!.add(new CandidateAttachment.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class CandidateAttachment {
  int? id;
  String? name;
  String? mimeType;
  String? size;
  String? createdAt;
  String? downloadUrl;
  String? viewUrl;
  bool? canDelete;

  CandidateAttachment(
      {this.id,
        this.name,
        this.mimeType,
        this.size,
        this.createdAt,
        this.downloadUrl,
        this.viewUrl,
        this.canDelete});

  CandidateAttachment.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    mimeType = json['mime_type'];
    size = json['size'];
    createdAt = json['created_at'];
    downloadUrl = json['download_url'];
    viewUrl = json['view_url'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['mime_type'] = this.mimeType;
    data['size'] = this.size;
    data['created_at'] = this.createdAt;
    data['download_url'] = this.downloadUrl;
    data['view_url'] = this.viewUrl;
    data['can_delete'] = this.canDelete;
    return data;
  }
}

class Permissions {
  bool? canDelete;

  Permissions({this.canDelete});

  Permissions.fromJson(Map<String, dynamic> json) {
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_delete'] = this.canDelete;
    return data;
  }
}
