class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<CandidateModel>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <CandidateModel>[];
      json['data'].forEach((v) {
        data!.add(new CandidateModel.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class CandidateModel {
  int? id;
  String? name;
  String? email;
  String? phone;
  String? position;
  String? source;
  CandidateStatus? status;
  List<Attachments>? attachments;
  List<Interviews>? interviews;
  String? createdAt;
  String? updatedAt;
  bool? canEdit;
  bool? canDelete;

  CandidateModel(
      {this.id,
        this.name,
        this.email,
        this.phone,
        this.position,
        this.source,
        this.status,
        this.attachments,
        this.interviews,
        this.createdAt,
        this.updatedAt,
        this.canEdit,
        this.canDelete});

  CandidateModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    phone = json['phone'];
    position = json['position'];
    source = json['source'];
    status =
    json['status'] != null ? new CandidateStatus.fromJson(json['status']) : null;
    if (json['attachments'] != null) {
      attachments = <Attachments>[];
      json['attachments'].forEach((v) {
        attachments!.add(new Attachments.fromJson(v));
      });
    }
    if (json['interviews'] != null) {
      interviews = <Interviews>[];
      json['interviews'].forEach((v) {
        interviews!.add(new Interviews.fromJson(v));
      });
    }
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['position'] = this.position;
    data['source'] = this.source;
    if (this.status != null) {
      data['status'] = this.status!.toJson();
    }
    if (this.attachments != null) {
      data['attachments'] = this.attachments!.map((v) => v.toJson()).toList();
    }
    if (this.interviews != null) {
      data['interviews'] = this.interviews!.map((v) => v.toJson()).toList();
    }
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}

class CandidateStatus {
  int? id;
  String? name;

  CandidateStatus({this.id, this.name});

  CandidateStatus.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}

class Attachments {
  int? id;
  String? fileName;
  String? url;
  String? size;
  String? mimeType;

  Attachments({this.id, this.fileName, this.url, this.size, this.mimeType});

  Attachments.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    fileName = json['file_name'];
    url = json['url'];
    size = json['size'];
    mimeType = json['mime_type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['file_name'] = this.fileName;
    data['url'] = this.url;
    data['size'] = this.size;
    data['mime_type'] = this.mimeType;
    return data;
  }
}

class Interviews {
  int? id;
  String? candidateName;
  String? interviewer;
  String? round;
  String? scheduledAt;
  String? status;
  String? location;
  String? mode;
  String? createdAt;
  String? updatedAt;

  Interviews(
      {this.id,
        this.candidateName,
        this.interviewer,
        this.round,
        this.scheduledAt,
        this.status,
        this.location,
        this.mode,
        this.createdAt,
        this.updatedAt});

  Interviews.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    candidateName = json['candidate_name'];
    interviewer = json['interviewer'];
    round = json['round'];
    scheduledAt = json['scheduled_at'];
    status = json['status'];
    location = json['location'];
    mode = json['mode'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['candidate_name'] = this.candidateName;
    data['interviewer'] = this.interviewer;
    data['round'] = this.round;
    data['scheduled_at'] = this.scheduledAt;
    data['status'] = this.status;
    data['location'] = this.location;
    data['mode'] = this.mode;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class Permissions {
  bool? canEdit;
  bool? canDelete;

  Permissions({this.canEdit, this.canDelete});

  Permissions.fromJson(Map<String, dynamic> json) {
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}
