class Autogenerated {
  bool? error;
  String? message;
  Data? data;

  Autogenerated({this.error, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  Candidate? candidate;

  Data({this.candidate});

  Data.fromJson(Map<String, dynamic> json) {
    candidate = json['candidate'] != null
        ? new Candidate.fromJson(json['candidate'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.candidate != null) {
      data['candidate'] = this.candidate!.toJson();
    }
    return data;
  }
}

class Candidate {
  int? id;
  String? name;
  String? email;
  String? phone;
  String? position;
  String? source;
  int? statusId;
  String? createdAt;
  String? updatedAt;
  List<Interviews>? interviews;

  Candidate(
      {this.id,
        this.name,
        this.email,
        this.phone,
        this.position,
        this.source,
        this.statusId,
        this.createdAt,
        this.updatedAt,
        this.interviews});

  Candidate.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    phone = json['phone'];
    position = json['position'];
    source = json['source'];
    statusId = json['status_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['interviews'] != null) {
      interviews = <Interviews>[];
      json['interviews'].forEach((v) {
        interviews!.add(new Interviews.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['phone'] = this.phone;
    data['position'] = this.position;
    data['source'] = this.source;
    data['status_id'] = this.statusId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.interviews != null) {
      data['interviews'] = this.interviews!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Interviews {
  int? id;
  int? candidateId;
  int? interviewerId;
  String? round;
  String? scheduledAt;
  String? mode;
  String? location;
  String? status;
  String? createdAt;
  String? updatedAt;
  Interviewer? interviewer;

  Interviews(
      {this.id,
        this.candidateId,
        this.interviewerId,
        this.round,
        this.scheduledAt,
        this.mode,
        this.location,
        this.status,
        this.createdAt,
        this.updatedAt,
        this.interviewer});

  Interviews.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    candidateId = json['candidate_id'];
    interviewerId = json['interviewer_id'];
    round = json['round'];
    scheduledAt = json['scheduled_at'];
    mode = json['mode'];
    location = json['location'];
    status = json['status'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    interviewer = json['interviewer'] != null
        ? new Interviewer.fromJson(json['interviewer'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['candidate_id'] = this.candidateId;
    data['interviewer_id'] = this.interviewerId;
    data['round'] = this.round;
    data['scheduled_at'] = this.scheduledAt;
    data['mode'] = this.mode;
    data['location'] = this.location;
    data['status'] = this.status;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.interviewer != null) {
      data['interviewer'] = this.interviewer!.toJson();
    }
    return data;
  }
}

class Interviewer {
  int? id;
  String? firstName;
  String? lastName;
  String? countryCode;
  String? countryIsoCode;
  String? phone;
  String? email;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zip;
  String? dob;
  String? doj;
  String? photo;
  String? avatar;
  int? activeStatus;
  int? darkMode;
  String? messengerColor;
  String? lang;
  String? emailVerifiedAt;
  String? defaultWorkspaceId;
  String? createdAt;
  String? updatedAt;
  int? status;

  Interviewer(
      {this.id,
        this.firstName,
        this.lastName,
        this.countryCode,
        this.countryIsoCode,
        this.phone,
        this.email,
        this.address,
        this.city,
        this.state,
        this.country,
        this.zip,
        this.dob,
        this.doj,
        this.photo,
        this.avatar,
        this.activeStatus,
        this.darkMode,
        this.messengerColor,
        this.lang,
        this.emailVerifiedAt,
        this.defaultWorkspaceId,
        this.createdAt,
        this.updatedAt,
        this.status});

  Interviewer.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    countryCode = json['country_code'];
    countryIsoCode = json['country_iso_code'];
    phone = json['phone'];
    email = json['email'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    dob = json['dob'];
    doj = json['doj'];
    photo = json['photo'];
    avatar = json['avatar'];
    activeStatus = json['active_status'];
    darkMode = json['dark_mode'];
    messengerColor = json['messenger_color'];
    lang = json['lang'];
    emailVerifiedAt = json['email_verified_at'];
    defaultWorkspaceId = json['default_workspace_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['country_code'] = this.countryCode;
    data['country_iso_code'] = this.countryIsoCode;
    data['phone'] = this.phone;
    data['email'] = this.email;
    data['address'] = this.address;
    data['city'] = this.city;
    data['state'] = this.state;
    data['country'] = this.country;
    data['zip'] = this.zip;
    data['dob'] = this.dob;
    data['doj'] = this.doj;
    data['photo'] = this.photo;
    data['avatar'] = this.avatar;
    data['active_status'] = this.activeStatus;
    data['dark_mode'] = this.darkMode;
    data['messenger_color'] = this.messengerColor;
    data['lang'] = this.lang;
    data['email_verified_at'] = this.emailVerifiedAt;
    data['default_workspace_id'] = this.defaultWorkspaceId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['status'] = this.status;
    return data;
  }
}
