class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<EstimateInvoicesModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <EstimateInvoicesModel>[];
      json['data'].forEach((v) {
        data!.add(new EstimateInvoicesModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class EstimateInvoicesModel {
  int? id;
  String? type;
  String? status;
  int? clientId;
  InvoiceClient? client;
  String? name;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zipCode;
  String? phone;
  String? note;
  String? personalNote;
  String? fromDate;
  String? toDate;
  String? total;
  String? taxAmount;
  String? finalTotal;
  String? createdAt;
  String? updatedAt;
  List<InvoicesItems>? items;

  EstimateInvoicesModel(
      {this.id,
        this.type,
        this.status,
        this.clientId,
        this.client,
        this.name,
        this.address,
        this.city,
        this.state,
        this.country,
        this.zipCode,
        this.phone,
        this.note,
        this.personalNote,
        this.fromDate,
        this.toDate,
        this.total,
        this.taxAmount,
        this.finalTotal,
        this.createdAt,
        this.updatedAt,
        this.items});

  EstimateInvoicesModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    type = json['type'];
    status = json['status'];
    clientId = json['client_id'];
    client =
    json['client'] != null ? new InvoiceClient.fromJson(json['client']) : null;
    name = json['name'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zipCode = json['zip_code'];
    phone = json['phone'];
    note = json['note'];
    personalNote = json['personal_note'];
    fromDate = json['from_date'];
    toDate = json['to_date'];
    total = json['total'];
    taxAmount = json['tax_amount'];
    finalTotal = json['final_total'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    if (json['items'] != null && json['items'] is List) {
      items = <InvoicesItems>[];
      json['items'].forEach((v) {
        // Check that each item is a map before trying to call fromJson
        if (v is Map<String, dynamic>) {
          items!.add(InvoicesItems.fromJson(v));
        }
      });
    }

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['type'] = this.type;
    data['status'] = this.status;
    data['client_id'] = this.clientId;
    if (this.client != null) {
      data['client'] = this.client!.toJson();
    }
    data['name'] = this.name;
    data['address'] = this.address;
    data['city'] = this.city;
    data['state'] = this.state;
    data['country'] = this.country;
    data['zip_code'] = this.zipCode;
    data['phone'] = this.phone;
    data['note'] = this.note;
    data['personal_note'] = this.personalNote;
    data['from_date'] = this.fromDate;
    data['to_date'] = this.toDate;
    data['total'] = this.total;
    data['tax_amount'] = this.taxAmount;
    data['final_total'] = this.finalTotal;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    if (this.items != null) {
      data['items'] = this.items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class InvoiceClient {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  InvoiceClient({this.id, this.firstName, this.lastName, this.email, this.photo});

  InvoiceClient.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    photo = json['photo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['photo'] = this.photo;
    return data;
  }
}

class InvoicesItems {
  int? id;
  String? name;
  String? description;
  String? quantity;
  EstimateInvoicesUnit? unit;
  String? rate;
  String? price;
  String? amount;
  double? percenatge;
  String? amt;
  String? title;
  String? unitId;
  String? unitName;
  String? tax;
  String? createdAt;
  String? updatedAt;

  bool isFromWidget; // <--- Add this new field

  InvoicesItems({
    this.id,
    this.name,
    this.description,
    this.quantity,
    this.unit,
    this.price,
    this.rate,
    this.amount,
    this.percenatge,
    this.amt,
    this.title,
    this.unitId,
    this.tax,
    this.unitName,
    this.createdAt,
    this.updatedAt,
    this.isFromWidget = false,
  });
  @override
  String toString() {
    return '''
InvoicesItems(
  id: $id,
  name: $name,
  description: $description,
  quantity: $quantity,
  unit: ${unit?.toString()},
  rate: $rate,
  price: $price,
  amount: $amount,
  percenatge: $percenatge,
  amt: $amt,
  title: $title,
  unitId: $unitId,
  unitName: $unitName,
  tax: $tax,
  createdAt: $createdAt,
  updatedAt: $updatedAt,
  isFromWidget: $isFromWidget
)''';
  }

  InvoicesItems.fromJson(Map<String, dynamic> json)
      : id = json['id'],
        name = json['name'],
        description = json['description'],
        quantity = json['quantity'],
        unit = json['unit'] is Map<String, dynamic>
            ? EstimateInvoicesUnit.fromJson(json['unit'])
            : null,

  rate = json['rate'],
        amount = json['amount'],
        price = json['price'],
        title = json['title'],
        tax = json['tax'],
        unitId = json['unit_id'],
        unitName = json['unit_name'],
        createdAt = json['created_at'],
        updatedAt = json['updated_at'],
        isFromWidget = json['is_from_widget'] ?? false;

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['id'] = id;
    data['name'] = name;
    data['description'] = description;
    data['quantity'] = quantity;
    if (unit != null) {
      data['unit'] = unit!.toJson();
    }
    data['rate'] = rate;
    data['amount'] = amount;
    data['price'] = price;
    data['title'] = title;
    data['tax'] = tax;
    data['unit_id'] = unitId;
    data['unit_name'] = unitName;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['is_from_widget'] = isFromWidget;
    return data;
  }

  InvoicesItems copyWith({
    int? id,
    String? name,
    String? description,
    String? quantity,
    EstimateInvoicesUnit? unit,
    String? rate,
    String? price,
    String? amount,
    String? title,
    String? tax,
    String? amt,
    String? percentage,
    String? unitId,
    String? unitName,
    String? createdAt,
    String? updatedAt,
    bool? isFromWidget,
  }) {
    return InvoicesItems(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      quantity: quantity ?? this.quantity,
      unit: unit ?? this.unit,
      amt: amt ?? this.amt,
      percenatge: percenatge ?? this.percenatge,
      rate: rate ?? this.rate,
      price: price ?? this.price,
      amount: amount ?? this.amount,
      title: title ?? this.title,
      tax: tax ?? this.tax,
      unitId: unitId ?? this.unitId,
      unitName: unitName ?? this.unitName,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}


class EstimateInvoicesUnit {
  int? id;
  int? workspaceId;
  String? title;
  String? description;
  String? createdAt;
  String? updatedAt;

  EstimateInvoicesUnit(
      {this.id,
        this.workspaceId,
        this.title,
        this.description,
        this.createdAt,
        this.updatedAt});

  EstimateInvoicesUnit.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    workspaceId = json['workspace_id'];
    title = json['title'];
    description = json['description'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['workspace_id'] = this.workspaceId;
    data['title'] = this.title;
    data['description'] = this.description;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
