class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<ExpenseModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <ExpenseModel>[];
      json['data'].forEach((v) {
        data!.add(new ExpenseModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ExpenseModel {
  int? id;
  String? title;
  int? expenseTypeId;
  String? expenseType;
  int? userId;
  UserExpenseModel? user;
  String? amount;
  String? expenseDate;
  String? note;
  String? createdBy;
  String? createdAt;

  ExpenseModel(
      {this.id,
        this.title,
        this.expenseTypeId,
        this.expenseType,
        this.userId,
        this.user,
        this.amount,
        this.expenseDate,
        this.note,
        this.createdBy,
        this.createdAt});

  ExpenseModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    expenseTypeId = json['expense_type_id'];
    expenseType = json['expense_type'];
    userId = json['user_id'];
    user = json['user'] != null ? new UserExpenseModel.fromJson(json['user']) : null;
    amount = json['amount'];
    expenseDate = json['expense_date'];
    note = json['note'];
    createdBy = json['created_by'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['expense_type_id'] = this.expenseTypeId;
    data['expense_type'] = this.expenseType;
    data['user_id'] = this.userId;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['amount'] = this.amount;
    data['expense_date'] = this.expenseDate;
    data['note'] = this.note;
    data['created_by'] = this.createdBy;
    data['created_at'] = this.createdAt;
    return data;
  }
}

class UserExpenseModel {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  UserExpenseModel({this.id, this.firstName, this.lastName, this.email, this.photo});

  UserExpenseModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    photo = json['photo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['photo'] = this.photo;
    return data;
  }
}
