class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<ExpenseTypeModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <ExpenseTypeModel>[];
      json['data'].forEach((v) {
        data!.add(new ExpenseTypeModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ExpenseTypeModel {
  int? id;
  String? title;
  String? description;
  String? createdAt;

  ExpenseTypeModel({this.id, this.title, this.description, this.createdAt});

  ExpenseTypeModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    description = json['description'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['description'] = this.description;
    data['created_at'] = this.createdAt;
    return data;
  }
}
