// class Autogenerated {
//   bool? error;
//   String? message;
//   int? total;
//   List<ItemsModel>? data;
//
//   Autogenerated({this.error, this.message, this.total, this.data});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     error = json['error'];
//     message = json['message'];
//     total = json['total'];
//     if (json['data'] != null) {
//       data = <ItemsModel>[];
//       json['data'].forEach((v) {
//         data!.add(new ItemsModel.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['error'] = this.error;
//     data['message'] = this.message;
//     data['total'] = this.total;
//     if (this.data != null) {
//       data['data'] = this.data!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
// class ItemsModel {
//   int? id;
//   String? title;
//   String? price;
//   int? unitId;
//   String? unitName;
//   String? description;
//   String? createdAt;
//   String? updatedAt;
//
//   ItemsModel(
//       {this.id,
//         this.title,
//         this.price,
//         this.unitId,
//         this.unitName,
//         this.description,
//         this.createdAt,
//         this.updatedAt});
//
//   ItemsModel.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     price = json['price'];
//     unitId = json['unit_id'];
//     unitName = json['unit_name'];
//     description = json['description'];
//     createdAt = json['created_at'];
//     updatedAt = json['updated_at'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['price'] = this.price;
//     data['unit_id'] = this.unitId;
//     data['unit_name'] = this.unitName;
//     data['description'] = this.description;
//     data['created_at'] = this.createdAt;
//     data['updated_at'] = this.updatedAt;
//     return data;
//   }
// }
