class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<PaymentModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <PaymentModel>[];
      json['data'].forEach((v) {
        data!.add(new PaymentModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PaymentModel {
  int? id;
  int? userId;
  UserPayment? user;
  int? invoiceId;
  String? invoice;
  int? paymentMethodId;
  String? paymentMethod;
  String? amount;
  String? paymentDate;
  String? note;
  String? createdBy;
  String? createdAt;
  String? updatedAt;

  PaymentModel(
      {this.id,
        this.userId,
        this.user,
        this.invoiceId,
        this.invoice,
        this.paymentMethodId,
        this.paymentMethod,
        this.amount,
        this.paymentDate,
        this.note,
        this.createdBy,
        this.createdAt,
        this.updatedAt});

  PaymentModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    user = json['user'] != null ? new UserPayment.fromJson(json['user']) : null;
    invoiceId = json['invoice_id'];
    invoice = json['invoice'];
    paymentMethodId = json['payment_method_id'];
    paymentMethod = json['payment_method'];
    amount = json['amount'];
    paymentDate = json['payment_date'];
    note = json['note'];
    createdBy = json['created_by'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['user_id'] = this.userId;
    if (this.user != null) {
      data['user'] = this.user!.toJson();
    }
    data['invoice_id'] = this.invoiceId;
    data['invoice'] = this.invoice;
    data['payment_method_id'] = this.paymentMethodId;
    data['payment_method'] = this.paymentMethod;
    data['amount'] = this.amount;
    data['payment_date'] = this.paymentDate;
    data['note'] = this.note;
    data['created_by'] = this.createdBy;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class UserPayment {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  UserPayment({this.id, this.firstName, this.lastName, this.email, this.photo});

  UserPayment.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    email = json['email'];
    photo = json['photo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['first_name'] = this.firstName;
    data['last_name'] = this.lastName;
    data['email'] = this.email;
    data['photo'] = this.photo;
    return data;
  }
}
