class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<TaxModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <TaxModel>[];
      json['data'].forEach((v) {
        data!.add(new TaxModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TaxModel {
  int? id;
  String? title;
  String? type;
  String? amount;
  int? percentage;
  String? createdAt;
  String? updatedAt;

  TaxModel(
      {this.id,
        this.title,
        this.type,
        this.amount,
        this.percentage,
        this.createdAt,
        this.updatedAt});

  TaxModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    type = json['type'];
    amount = json['amount'];
    percentage = json['percentage'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['type'] = this.type;
    data['amount'] = this.amount;
    data['percentage'] = this.percentage;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}
