class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<Tasks>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <Tasks>[];
      json['data'].forEach((v) {
        data!.add(new Tasks.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Tasks {
  int? id;
  int? workspaceId;
  String? title;
  String? status;
  int? statusId;
  String? priority;
  int? priorityId;
  List<TaskUsers>? users;
  List<int>? userId;
  List<TaskClients>? clients;
  String? startDate;
  String? dueDate;
  String? project;
  int? projectId;
  String? description;
  String? note;
  int? favorite;
  int? pinned;
  int? clientCanDiscuss;
  String? createdAt;
  String? updatedAt;
  int? enableReminder;
  String? lastReminderSent;
  String? frequencyType;
  int? dayOfWeek;
  int? dayOfMonth;
  String? timeOfDay;
  int? enableRecurringTask;
  String? recurrenceFrequency;
  int? recurrenceDayOfWeek;
  int? recurrenceDayOfMonth;
  int? recurrenceMonthOfYear;
  String? recurrenceStartsFrom;
  int? recurrenceOccurrences; // Updated to handle int or String
  int? completedOccurrences;
  String? billingType;
  int? completionPercentage;
  List<int>? taskListId;

  List<CustomFieldsTask>? customFields;
  CustomFieldValuesTask? customFieldValues;

  Tasks(
      {this.id,
        this.workspaceId,
        this.title,
        this.status,
        this.statusId,
        this.priority,
        this.priorityId,
        this.users,
        this.userId,
        this.clients,
        this.startDate,
        this.dueDate,
        this.project,
        this.projectId,
        this.description,
        this.note,
        this.favorite,
        this.pinned,
        this.clientCanDiscuss,
        this.createdAt,
        this.updatedAt,
        this.enableReminder,
        this.lastReminderSent,
        this.frequencyType,
        this.dayOfWeek,
        this.dayOfMonth,
        this.timeOfDay,
        this.enableRecurringTask,
        this.recurrenceFrequency,
        this.recurrenceDayOfWeek,
        this.recurrenceDayOfMonth,
        this.recurrenceMonthOfYear,
        this.recurrenceStartsFrom,
        this.recurrenceOccurrences,
        this.completedOccurrences,
        this.billingType,
        this.completionPercentage,
        this.taskListId,
        this.customFields,
        this.customFieldValues});

  Tasks.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    workspaceId = json['workspace_id'];
    title = json['title'];
    status = json['status'];
    statusId = json['status_id'];
    priority = json['priority'];
    priorityId = json['priority_id'];
    if (json['users'] != null && json['users'] is List) {
      users = <TaskUsers>[];
      for (var v in (json['users'] as List)) {
        if (v is Map<String, dynamic>) {
          users!.add(TaskUsers.fromJson(v));
        }
      }
    }

    userId = json['user_id']?.cast<int>();

    if (json['clients'] != null && json['clients'] is List) {
      clients = <TaskClients>[];
      for (var v in (json['clients'] as List)) {
        if (v is Map<String, dynamic>) {
          clients!.add(TaskClients.fromJson(v));
        }
      }
    }

    startDate = json['start_date'];
    dueDate = json['due_date'];
    project = json['project'];
    projectId = json['project_id'];
    description = json['description'];
    note = json['note'];
    favorite = json['favorite'];
    pinned = json['pinned'];
    clientCanDiscuss = json['client_can_discuss'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    enableReminder = json['enable_reminder'];
    lastReminderSent = json['last_reminder_sent'];
    frequencyType = json['frequency_type'];
    dayOfWeek = json['day_of_week'];
    dayOfMonth = json['day_of_month'];
    timeOfDay = json['time_of_day'];
    enableRecurringTask = json['enable_recurring_task'];
    recurrenceFrequency = json['recurrence_frequency'];
    recurrenceDayOfWeek = json['recurrence_day_of_week'];
    recurrenceDayOfMonth = json['recurrence_day_of_month'];
    recurrenceMonthOfYear = json['recurrence_month_of_year'];
    recurrenceStartsFrom = json['recurrence_starts_from'];
    recurrenceOccurrences = json['recurrence_occurrences'];
    completedOccurrences = json['completed_occurrences'];
    billingType = json['billing_type'];
    completionPercentage = json['completion_percentage'];
    taskListId = json['task_list_id'];
    if (json['customFields'] != null) {
      customFields = <CustomFieldsTask>[];
      json['customFields'].forEach((v) {
        customFields!.add(new CustomFieldsTask.fromJson(v));
      });
    }
    if (json['customFieldValues'] != null) {
      if (json['customFieldValues'] is Map<String, dynamic>) {
        customFieldValues = CustomFieldValuesTask.fromJson(json['customFieldValues']);
      } else {
        // handle unexpected format or fallback
        customFieldValues = CustomFieldValuesTask(values: {});
      }
    }

  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['workspace_id'] = workspaceId;
    data['title'] = title;
    data['status'] = status;
    data['status_id'] = statusId;
    data['priority'] = priority;
    data['priority_id'] = priorityId;
    data['favorite'] = favorite;
    data['pinned'] = pinned;

    if (users != null) {
      data['users'] = users!.map((v) => v.toJson()).toList();
    }

    data['user_id'] = userId;

    if (clients != null) {
      data['clients'] = clients!.map((v) => v.toJson()).toList();
    }

    data['start_date'] = startDate;
    data['due_date'] = dueDate;
    data['project'] = project;
    data['project_id'] = projectId;
    data['description'] = description;
    data['note'] = note;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['enable_reminder'] = enableReminder;
    data['frequency_type'] = frequencyType;
    data['day_of_week'] = dayOfWeek;
    data['day_of_month'] = dayOfMonth;
    data['time_of_day'] = timeOfDay;
    data['enable_recurring_task'] = enableRecurringTask;
    data['recurrence_frequency'] = recurrenceFrequency;
    data['recurrence_day_of_week'] = recurrenceDayOfWeek;
    data['recurrence_day_of_month'] = recurrenceDayOfMonth;
    data['recurrence_month_of_year'] = recurrenceMonthOfYear;
    data['recurrence_starts_from'] = recurrenceStartsFrom;
    data['recurrence_occurrences'] = recurrenceOccurrences;
    data['completed_occurrences'] = completedOccurrences;
    data['billing_type'] = billingType;
    data['completion_percentage'] = completionPercentage;
    data['task_list_id'] = taskListId;
    if (this.customFields != null) {
      data['customFields'] = this.customFields!.map((v) => v.toJson()).toList();
    }
    if (customFieldValues != null) {
      data['customFieldValues'] = customFieldValues!.toJson()['values'];
    }
    return data;
  }
  factory Tasks.empty() {
    return Tasks(
      id: 0,
      workspaceId: 0,
      title: "",
      status: "",
      statusId: 0,
      priority: "",
      priorityId: 0,
      users: [],
      userId: [],
      clients: [],
      startDate: "",
      dueDate: "",
      project: "",
      projectId: 0,
      description: "",
      note: "",
      favorite: 0,
      pinned: 0,
      clientCanDiscuss: 0,
      createdAt: "",
      updatedAt: "",
      enableReminder: 0,
      lastReminderSent: "",
      frequencyType: "",
      dayOfWeek: 0,
      dayOfMonth: 0,
      timeOfDay: "",
      enableRecurringTask: 0,
      recurrenceFrequency: "",
      recurrenceDayOfWeek: 0,
      recurrenceDayOfMonth: 0,
      recurrenceMonthOfYear: 0,
      recurrenceStartsFrom: "",
      recurrenceOccurrences: 0,
      completedOccurrences: 0,
      billingType: "",
      completionPercentage: 0,
      taskListId: [],
      customFields: [],
      customFieldValues: null,
    );
  }
  @override
  String toString() {
    return 'Task(id: $customFieldValues, title: $customFields)';
  }
}

class CustomFieldsTask {
  int? id;
  String? module;
  String? fieldLabel;
  String? name;
  String? fieldType;
  String? guideText;
  List<String>? options;
  String? required;
  String? visibility;
  String? createdAt;
  String? updatedAt;

  CustomFieldsTask(
      {this.id,
        this.module,
        this.fieldLabel,
        this.name,
        this.fieldType,
        this.guideText,
        this.options,
        this.required,
        this.visibility,
        this.createdAt,
        this.updatedAt});

  CustomFieldsTask.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    module = json['module'];
    fieldLabel = json['field_label'];
    name = json['name'];
    fieldType = json['field_type'];
    guideText = json['guide_text'];
    options = json['options'] != null ? (json['options'] as List).cast<String>() : [];
    required = json['required'];
    visibility = json['visibility'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['module'] = this.module;
    data['field_label'] = this.fieldLabel;
    data['name'] = this.name;
    data['field_type'] = this.fieldType;
    data['guide_text'] = this.guideText;
    data['options'] = this.options;
    data['required'] = this.required;
    data['visibility'] = this.visibility;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    return data;
  }
}

class CustomFieldValuesTask {
  Map<String, dynamic> values;

  CustomFieldValuesTask({required this.values});

  factory CustomFieldValuesTask.fromJson(Map<String, dynamic> json) {
    return CustomFieldValuesTask(values: json);
  }

  Map<String, dynamic> toJson() {
    return values;
  }
}
class TaskUsers {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  TaskUsers({this.id, this.firstName, this.lastName, this.photo, this.email});

  TaskUsers.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}

class TaskClients {
  int? id;
  String? firstName;
  String? lastName;
  String? email;
  String? photo;

  TaskClients({this.id, this.firstName, this.lastName, this.photo, this.email});

  TaskClients.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    photo = json['photo'];
    email = json['email'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['photo'] = photo;
    data['email'] = email;
    return data;
  }
}