class Autogenerated {
  bool? error;
  List<CommentModel>? comments;

  Autogenerated({this.error, this.comments});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    if (json['comments'] != null) {
      comments = <CommentModel>[];
      json['comments'].forEach((v) {
        comments!.add(CommentModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['error'] = error;
    if (comments != null) {
      data['comments'] = comments!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  Autogenerated copyWith({
    bool? error,
    List<CommentModel>? comments,
  }) {
    return Autogenerated(
      error: error ?? this.error,
      comments: comments ?? this.comments,
    );
  }
}

class CommentModel {
  final String? id;
  final String? content;
  final String? sentTime;
  final String? createdAt;
  final Commenter? commenter;
  final List<CommentsAttachments>? attachments;
  final List<CommentModel>? children;
  final bool isTemporary; // Added isTemporary field

  CommentModel({
    this.id,
    this.content,
    this.sentTime,
    this.createdAt,
    this.commenter,
    this.attachments,
    this.children,
    this.isTemporary = false, // Default to false
  });

  CommentModel copyWith({
    String? id,
    String? content,
    String? sentTime,
    String? createdAt,
    Commenter? commenter,
    List<CommentsAttachments>? attachments,
    List<CommentModel>? children,
    bool? isTemporary,
  }) {
    return CommentModel(
      id: id ?? this.id,
      content: content ?? this.content,
      sentTime: sentTime ?? this.sentTime,
      createdAt: createdAt ?? this.createdAt,
      commenter: commenter ?? this.commenter,
      attachments: attachments ?? this.attachments,
      children: children ?? this.children,
      isTemporary: isTemporary ?? this.isTemporary,
    );
  }

  factory CommentModel.fromJson(Map<String, dynamic> json) {
    return CommentModel(
      id: json['id']?.toString(),
      content: json['content'],
      sentTime: json['sent_time'],
      createdAt: json['created_at'],
      commenter: json['commenter'] != null
          ? Commenter.fromJson(json['commenter'])
          : null,
      attachments: json['attachments'] != null
          ? (json['attachments'] as List)
          .map((e) => CommentsAttachments.fromJson(e))
          .toList()
          : [],
      children: json['children'] != null
          ? (json['children'] as List)
          .map((e) => CommentModel.fromJson(e))
          .toList()
          : [],
      isTemporary: json['isTemporary'] ?? false,
    );
  }
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'content': content,
      'sent_time': sentTime,
      'created_at': createdAt,
      'commenter': commenter?.toJson(),
      'attachments': attachments?.map((e) => e.toJson()).toList(),
      'children': children?.map((e) => e.toJson()).toList(),
      'isTemporary': isTemporary,
    };
  }
  void printCommentModel() {
    final json = toJson();
    json.forEach((key, value) {
      print('PLEASE LOOK INTO IT $key: $value');
    });
  }
}

class Commenter {
  int? id;
  String? firstName;
  String? lastName;
  String? countryCode;
  String? countryIsoCode;
  String? phone;
  String? email;
  String? address;
  String? city;
  String? state;
  String? country;
  String? zip;
  String? dob;
  String? doj;
  String? photo;
  String? avatar;
  int? activeStatus;
  int? darkMode;
  String? messengerColor;
  String? lang;
  String? emailVerifiedAt;
  String? defaultWorkspaceId;
  String? createdAt;
  String? updatedAt;
  int? status;

  Commenter({
    this.id,
    this.firstName,
    this.lastName,
    this.countryCode,
    this.countryIsoCode,
    this.phone,
    this.email,
    this.address,
    this.city,
    this.state,
    this.country,
    this.zip,
    this.dob,
    this.doj,
    this.photo,
    this.avatar,
    this.activeStatus,
    this.darkMode,
    this.messengerColor,
    this.lang,
    this.emailVerifiedAt,
    this.defaultWorkspaceId,
    this.createdAt,
    this.updatedAt,
    this.status,
  });

  Commenter.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    firstName = json['first_name'];
    lastName = json['last_name'];
    countryCode = json['country_code'];
    countryIsoCode = json['country_iso_code'];
    phone = json['phone'];
    email = json['email'];
    address = json['address'];
    city = json['city'];
    state = json['state'];
    country = json['country'];
    zip = json['zip'];
    dob = json['dob'];
    doj = json['doj'];
    photo = json['photo'];
    avatar = json['avatar'];
    activeStatus = json['active_status'];
    darkMode = json['dark_mode'];
    messengerColor = json['messenger_color'];
    lang = json['lang'];
    emailVerifiedAt = json['email_verified_at'];
    defaultWorkspaceId = json['default_workspace_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['country_code'] = countryCode;
    data['country_iso_code'] = countryIsoCode;
    data['phone'] = phone;
    data['email'] = email;
    data['address'] = address;
    data['city'] = city;
    data['state'] = state;
    data['country'] = country;
    data['zip'] = zip;
    data['dob'] = dob;
    data['doj'] = doj;
    data['photo'] = photo;
    data['avatar'] = avatar;
    data['active_status'] = activeStatus;
    data['dark_mode'] = darkMode;
    data['messenger_color'] = messengerColor;
    data['lang'] = lang;
    data['email_verified_at'] = emailVerifiedAt;
    data['default_workspace_id'] = defaultWorkspaceId;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['status'] = status;
    return data;
  }

  Commenter copyWith({
    int? id,
    String? firstName,
    String? lastName,
    String? countryCode,
    String? countryIsoCode,
    String? phone,
    String? email,
    String? address,
    String? city,
    String? state,
    String? country,
    String? zip,
    String? dob,
    String? doj,
    String? photo,
    String? avatar,
    int? activeStatus,
    int? darkMode,
    String? messengerColor,
    String? lang,
    String? emailVerifiedAt,
    String? defaultWorkspaceId,
    String? createdAt,
    String? updatedAt,
    int? status,
  }) {
    return Commenter(
      id: id ?? this.id,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      countryCode: countryCode ?? this.countryCode,
      countryIsoCode: countryIsoCode ?? this.countryIsoCode,
      phone: phone ?? this.phone,
      email: email ?? this.email,
      address: address ?? this.address,
      city: city ?? this.city,
      state: state ?? this.state,
      country: country ?? this.country,
      zip: zip ?? this.zip,
      dob: dob ?? this.dob,
      doj: doj ?? this.doj,
      photo: photo ?? this.photo,
      avatar: avatar ?? this.avatar,
      activeStatus: activeStatus ?? this.activeStatus,
      darkMode: darkMode ?? this.darkMode,
      messengerColor: messengerColor ?? this.messengerColor,
      lang: lang ?? this.lang,
      emailVerifiedAt: emailVerifiedAt ?? this.emailVerifiedAt,
      defaultWorkspaceId: defaultWorkspaceId ?? this.defaultWorkspaceId,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      status: status ?? this.status,
    );
  }
}

class CommentsAttachments {
  int? id;
  String? fileName;
  String? filePath;
  String? fileType;
  String? url;

  CommentsAttachments({
    this.id,
    this.fileName,
    this.filePath,
    this.fileType,
    this.url,
  });

  CommentsAttachments.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    fileName = json['file_name'];
    filePath = json['file_path'];
    fileType = json['file_type'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['file_name'] = fileName;
    data['file_path'] = filePath;
    data['file_type'] = fileType;
    data['url'] = url;
    return data;
  }

  CommentsAttachments copyWith({
    int? id,
    String? fileName,
    String? filePath,
    String? fileType,
    String? url,
  }) {
    return CommentsAttachments(
      id: id ?? this.id,
      fileName: fileName ?? this.fileName,
      filePath: filePath ?? this.filePath,
      fileType: fileType ?? this.fileType,
      url: url ?? this.url,
    );
  }
}

class Children {
  int? id;
  String? content;
  Commenter? commenter;
  String? createdAt;
  String? sentTime;
  List<CommentsAttachments>? attachments;
  List<Children>? children;

  Children({
    this.id,
    this.content,
    this.commenter,
    this.createdAt,
    this.sentTime,
    this.attachments,
    this.children,
  });

  Children.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    content = json['content'];
    commenter = json['commenter'] != null
        ? Commenter.fromJson(json['commenter'])
        : null;
    createdAt = json['created_at'];
    sentTime = json['sent_time'];
    if (json['attachments'] != null) {
      attachments = <CommentsAttachments>[];
      json['attachments'].forEach((v) {
        attachments!.add(CommentsAttachments.fromJson(v));
      });
    }
    if (json['children'] != null) {
      children = <Children>[];
      json['children'].forEach((v) {
        children!.add(Children.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['content'] = content;
    if (commenter != null) {
      data['commenter'] = commenter!.toJson();
    }
    data['created_at'] = createdAt;
    data['sent_time'] = sentTime;
    if (attachments != null) {
      data['attachments'] = attachments!.map((v) => v.toJson()).toList();
    }
    if (children != null) {
      data['children'] = children!.map((v) => v.toJson()).toList();
    }
    return data;
  }

  Children copyWith({
    int? id,
    String? content,
    Commenter? commenter,
    String? createdAt,
    String? sentTime,
    List<CommentsAttachments>? attachments,
    List<Children>? children,
  }) {
    return Children(
      id: id ?? this.id,
      content: content ?? this.content,
      commenter: commenter ?? this.commenter,
      createdAt: createdAt ?? this.createdAt,
      sentTime: sentTime ?? this.sentTime,
      attachments: attachments ?? this.attachments,
      children: children ?? this.children,
    );
  }
}
