class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<ContractModel>? data;

  Autogenerated({this.error, this.message, this.total, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <ContractModel>[];
      json['data'].forEach((v) {
        data!.add(new ContractModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ContractModel {
  int? id;
  String? title;
  String? value;
  String? startDate;
  String? endDate;
  Client? client;
  CreatedBy? createdBy;
  Project? project;
  ContractType? contractType;
  String? description;
  int? workspaceId;
  String? createdAt;
  String? updatedAt;
  String? status;
  Signatures? signatures;
  String? duration;

  ContractModel(
      {this.id,
        this.title,
        this.value,
        this.startDate,
        this.endDate,
        this.client,
        this.createdBy,
        this.project,
        this.contractType,
        this.description,
        this.workspaceId,
        this.createdAt,
        this.updatedAt,
        this.status,
        this.signatures,
        this.duration});
  factory ContractModel.empty() {
    return ContractModel(
      id: 0,
      title: '',
      value: '',
      startDate: '',
      endDate: '',
      client: Client.empty(),
      createdBy: CreatedBy.empty(),
      project: Project.empty(),
      contractType: ContractType.empty(),
      description: '',
      workspaceId: 0,
      createdAt: '',
      updatedAt: '',
      status: '',
      signatures: Signatures.empty(),
      duration: '',
    );
  }

  ContractModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    value = json['value'];
    startDate = json['start_date'];
    endDate = json['end_date'];
    client =
    json['client'] != null ? new Client.fromJson(json['client']) : null;
    createdBy = json['created_by'] != null
        ? new CreatedBy.fromJson(json['created_by'])
        : null;
    project =
    json['project'] != null ? new Project.fromJson(json['project']) : null;
    contractType = json['contract_type'] != null
        ? new ContractType.fromJson(json['contract_type'])
        : null;
    description = json['description'];
    workspaceId = json['workspace_id'];
    createdAt = json['created_at'];
    updatedAt = json['updated_at'];
    status = json['status'];
    signatures = json['signatures'] != null
        ? new Signatures.fromJson(json['signatures'])
        : null;
    duration = json['duration'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['value'] = this.value;
    data['start_date'] = this.startDate;
    data['end_date'] = this.endDate;
    if (this.client != null) {
      data['client'] = this.client!.toJson();
    }
    if (this.createdBy != null) {
      data['created_by'] = this.createdBy!.toJson();
    }
    if (this.project != null) {
      data['project'] = this.project!.toJson();
    }
    if (this.contractType != null) {
      data['contract_type'] = this.contractType!.toJson();
    }
    data['description'] = this.description;
    data['workspace_id'] = this.workspaceId;
    data['created_at'] = this.createdAt;
    data['updated_at'] = this.updatedAt;
    data['status'] = this.status;
    if (this.signatures != null) {
      data['signatures'] = this.signatures!.toJson();
    }
    data['duration'] = this.duration;
    return data;
  }
}

class Client {
  int? id;
  String? name;
  String? email;
  String? profilePicture;

  Client({this.id, this.name, this.email, this.profilePicture});
  factory Client.empty() {
    return Client(
      id: 0,
      name: '',
      email: '',
      profilePicture: '',
    );
  }

  Client.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    email = json['email'];
    profilePicture = json['profile_picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['profile_picture'] = this.profilePicture;
    return data;
  }
}

class CreatedBy {
  String? type;
  int? id;
  String? name;
  String? email;
  String? profilePicture;

  CreatedBy({this.type, this.id, this.name, this.email, this.profilePicture});
  factory CreatedBy.empty() {
    return CreatedBy(
      type: '',
      id: 0,
      name: '',
      email: '',
      profilePicture: '',
    );
  }

  CreatedBy.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    id = json['id'];
    name = json['name'];
    email = json['email'];
    profilePicture = json['profile_picture'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['id'] = this.id;
    data['name'] = this.name;
    data['email'] = this.email;
    data['profile_picture'] = this.profilePicture;
    return data;
  }
}

class Project {
  int? id;
  String? title;

  Project({this.id, this.title});
  factory Project.empty() {
    return Project(
      id: 0,
      title: '',
    );
  }

  Project.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    return data;
  }
}

class ContractType {
  int? id;
  String? name;

  ContractType({this.id, this.name});
  factory ContractType.empty() {
    return ContractType(
      id: 0,
      name: '',
    );
  }

  ContractType.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    return data;
  }
}

class Signatures {
  Promisor? promisor;
  Promisee? promisee;

  Signatures({this.promisor, this.promisee});
  factory Signatures.empty() {
    return Signatures(
      promisor: Promisor.empty(),
      promisee: Promisee.empty(),
    );
  }

  Signatures.fromJson(Map<String, dynamic> json) {
    promisor = json['promisor'] != null
        ? new Promisor.fromJson(json['promisor'])
        : null;
    promisee = json['promisee'] != null
        ? new Promisee.fromJson(json['promisee'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.promisor != null) {
      data['promisor'] = this.promisor!.toJson();
    }
    if (this.promisee != null) {
      data['promisee'] = this.promisee!.toJson();
    }
    return data;
  }
}

class Promisor {
  String? status;
  String? url;

  Promisor({this.status, this.url});
  factory Promisor.empty() {
    return Promisor(
      status: '',
      url: '',
    );
  }

  Promisor.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['url'] = this.url;
    return data;
  }
}

class Promisee {
  String? status;
  String? url;

  Promisee({this.status, this.url});
  factory Promisee.empty() {
    return Promisee(
      status: '',
      url: '',
    );
  }

  Promisee.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    url = json['url'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['status'] = this.status;
    data['url'] = this.url;
    return data;
  }
}
