class Autogenerated {
  bool? error;
  String? message;
  int? total;
  List<InterviewModel>? data;
  Permissions? permissions;

  Autogenerated(
      {this.error, this.message, this.total, this.data, this.permissions});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    error = json['error'];
    message = json['message'];
    total = json['total'];
    if (json['data'] != null) {
      data = <InterviewModel>[];
      json['data'].forEach((v) {
        data!.add(new InterviewModel.fromJson(v));
      });
    }
    permissions = json['permissions'] != null
        ? new Permissions.fromJson(json['permissions'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['error'] = this.error;
    data['message'] = this.message;
    data['total'] = this.total;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    if (this.permissions != null) {
      data['permissions'] = this.permissions!.toJson();
    }
    return data;
  }
}

class InterviewModel {
  int? id;
  int? candidateId;
  String? candidateName;
  int? interviewerId;
  String? interviewerName;
  String? round;
  String? scheduledAt;
  String? mode;
  String? location;
  String? status;
  bool? canEdit;
  bool? canDelete;

  InterviewModel(
      {this.id,
        this.candidateId,
        this.interviewerName,
        this.candidateName,
        this.interviewerId,
        this.round,
        this.scheduledAt,
        this.mode,
        this.location,
        this.status,
        this.canEdit,
        this.canDelete});

  InterviewModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    candidateId = json['candidate_id'];
    candidateName = json['candidate_name'];
    interviewerName = json['interviewer_name'];
    interviewerId = json['interviewer_id'];
    round = json['round'];
    scheduledAt = json['scheduled_at'];
    mode = json['mode'];
    location = json['location'];
    status = json['status'];
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['candidate_id'] = this.candidateId;
    data['interviewer_id'] = this.interviewerId;
    data['round'] = this.round;
    data['scheduled_at'] = this.scheduledAt;
    data['mode'] = this.mode;
    data['location'] = this.location;
    data['status'] = this.status;
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}

class Permissions {
  bool? canEdit;
  bool? canDelete;

  Permissions({this.canEdit, this.canDelete});

  Permissions.fromJson(Map<String, dynamic> json) {
    canEdit = json['can_edit'];
    canDelete = json['can_delete'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['can_edit'] = this.canEdit;
    data['can_delete'] = this.canDelete;
    return data;
  }
}
